<?php namespace Bet\Hydrator;

use Zend\Stdlib\Hydrator\ClassMethods;

/**
 * Class BetHydrator
 *
 * @package Bet\Hydrator
 */
class BetHydrator extends ClassMethods
{
    /**
     * @var BetBetLinesHydrator
     */
    protected $linesHydrator;

    /**
     * BetHydrator constructor.
     *
     * @param bool $underscoreSeparatedKeys
     * @param BetBetLinesHydrator $linesHydrator
     */
    public function __construct($underscoreSeparatedKeys = true, BetBetLinesHydrator $linesHydrator)
    {
        parent::__construct($underscoreSeparatedKeys);

        $this->linesHydrator = $linesHydrator;

        $this->addStrategy('lines', $this->linesHydrator);
    }

    /**
     * @param object $object
     * @return array
     */
    public function extract($object)
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @param object $object
     * @return object
     */
    public function hydrate(array $data, $object)
    {
        if(!isset($data['successful'])) {
            $data['successful'] = 0;
        } else {
            $data['successful'] = 1;
        }

        $this->linesHydrator->setContext($object);

        return parent::hydrate($data, $object);
    }

}