<?php namespace Bet\Hydrator;

use Zend\Stdlib\Hydrator\ClassMethods;

/**
 * Class BetHydrator
 *
 * @package Bet\Hydrator
 */
class BetLineHydrator extends ClassMethods
{

    /**
     * BetLineHydrator constructor.
     * @param bool $underscoreSeparatedKeys
     */
    public function __construct($underscoreSeparatedKeys = true)
    {
        parent::__construct($underscoreSeparatedKeys);
    }

    /**
     * @param array $data
     * @param object $object
     * @return object
     */
    public function hydrate(array $data, $object)
    {
        //todo: remove, temp until matches supported.
        unset($data['match']);

        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }
}