<h1> Delete a bet </h1>

<?php
    echo $this->form()->openTag($form);

    $form->setAttribute('action', $this->url('bet', array('action' => 'add')));
    $form->prepare();

    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('userId'));
?>
<div class="form-group">
    <label>Are you sure you want to delete:</label>
    <?php
    echo $this->formRow($form->get('name'));
    ?>
</div>
<div class="form-group">
    <label>If so, enter the name below & then click delete.</label>
    <?php
    echo $this->formRow($form->get('confirmation'));
    ?>
</div>

<div class="form-group">
    <?php
    echo $this->formRow($form->get('submit'));
    ?>
</div>

<?php
echo $this->form()->closeTag($form);


