<h1> Update an entry</h1>

<?php
echo $this->form()->openTag($form);
$form->setAttribute('action', $this->url('bet', array('action' => 'edit')));
$form->get('id')->setAttribute('type', 'text');
$form->get('submit')->setAttribute('value', 'Update');
$form->prepare();


echo $this->formInput($form->get('id'));
//TODO user_accounts - remove
echo $this->formHidden($form->get('userId'));
echo $this->formRow($form->get('name'));

echo $this->formInput($form->get('submit'));

echo $this->form()->closeTag($form);