<h1> Update bet </h1>

<?php

echo $this->form()->openTag($form);

$form->setAttribute('action', $this->url('bet', array('action' => 'edit')));
$form->get('id')->setAttribute('type', 'text');
$form->get('submit')->setAttribute('value', 'Update');
$form->prepare();


echo $this->formHidden($form->get('id'));

echo $this->formHidden($form->get('userId'));


echo $this->partial('partials/bet/form', array('form' => $form));
echo $this->form()->closeTag($form);