<h3><?php echo $this->title; ?></h3>

<div class="row">
    <div class="col-lg-6 ">
        <?php echo $this->form()->openTag($form); ?>

        <?php
        echo $this->formHidden($form->get('id'));
        echo $this->formHidden($form->get('userId'));
        ?>

        <div class="form-group" id="match-name">
            <?php echo $this->formRow($form->get('name')); ?>

            <div class="modal fade alt-option" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Select a match...</h4>
                        </div>
                        <div class="modal-body">
                            <select name="alt-value">
                                <?php foreach ($this->matches as $label => $matches) : ?>
                                    <optgroup label="<?php echo $label ?>">
                                        <?php foreach ($matches as $match_id => $match) : ?>
                                            <option id="<?php echo $match_id ?>">
                                                <?php echo $match ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary alt-select">Select</button>
                        </div>
                    </div>
                </div>
            </div>

            <button class="btn btn-small btn-default show-alt-option">Select event...</button>
        </div>

        <div class="form-group">
            <?php echo $this->formRow($form->get('date')); ?>
        </div>

        <div id="bet-entry">
            <bet-entry amount="<?php echo $form->get('amount')->getValue() ?>"
                       winnings="<?php echo $form->get('return')->getValue() ?>">
            </bet-entry>
        </div>


        <div class="checkbox">
            <?php
            echo $this->formLabel($form->get('successful'));
            echo $this->formCheckbox($form->get('successful'));
            ?>
        </div>

        <?php echo $this->formRow($form->get('secret')); ?>
        <?php echo $this->formInput($form->get('submit')); ?>

        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>

<?php $this->HeadScript()->appendFile($this->basePath() . '/js/bet/form.js');?>
