<h1><?php echo $this->title; ?></h1>

<?php echo $this->form()->openTag($form);?>

        <?php
            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('userId'));
        ?>

            <div class="form-group">
                <?php echo $this->formRow($form->get('name')); ?>
            </div>

            <div class="form-group">
                <?php echo $this->formRow($form->get('date')); ?>
            </div>

            <div class="form-group">
                <?php echo $this->formRow($form->get('amount')); ?>
            </div>

            <div class="form-group">
                <?php echo $this->formRow($form->get('return')); ?>
            </div>


        <div class="checkbox">
            <?php
                echo $this->formLabel($form->get('successful'));
                echo $this->formCheckbox($form->get('successful'));
            ?>
        </div>

        <?php echo $this->formRow($form->get('secret')); ?>
        <?php echo $this->formInput($form->get('submit')); ?>

<?php echo $this->form()->closeTag($form);