<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?php
        echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))
            ->setSeparator(' - ')
            ->setAutoEscape(false)
    ?>

    <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/form-plugin.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')

        ->prependStylesheet($this->basePath() . '/css/sb-admin.css')
        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
    ?>

    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>

    <!-- Scripts -->
    <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/startup.js')
            ->prependFile($this->basePath() . '/bower_components/requirejs/require.js')
            ->prependFile($this->basePath() . '/js/require.config.js');
    ?>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <li>
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo $this->translate('Bets') ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url('bet') ?>"><?php echo $this->translate('List') ?></a>
                                <a href="<?php echo $this->url('bet', array('action'=>'add')) ?>"><?php echo $this->translate('Add') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo $this->translate('Scraper') ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url('scraper') ?>"><?php echo $this->translate('Sources') ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container" id="content-section">
        <?php
            if(isset($messages) && $messages->any()) {
                echo $this->partial('partials/messages', array('messages' => $messages));
            }
        ?>

        <?php echo $this->content; ?>

    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
